### ISSUE TITLE
Display all upcoming events from Meetup API

### ISSUE THREAD

**Issue by hbrysiewicz** [sandiegojs/sandiegojs#2]
Display Event data returned from Meetup API. Currently blocked by sandiegojs/sandiegojs-api#1 which will return the Events in [JSONAPI](http://jsonapi.org) format, which is expected by ember-data. 

The [Meetup API documentation](https://www.meetup.com/meetup_api/docs/) provides a listing of all data returned by the [/events](https://www.meetup.com/meetup_api/docs/:urlname/events/#list) endpoint.
## Subtasks
- [x] Create models for Event, Venue and Group
- [ ] Create a route for listing the events
- [ ] Component to display single event summary details
- [ ] Component to list all summary details for each event
- [ ] Implement the above components on the `events` route
- [ ] Testing!
## Resources

[Join our Slack](http://sandiegojs.herokuapp.com/) and join the `#sdjs-website` channel
Checkout the [sandiegojs-api](http://github.com/sandiegojs/sandiegojs-api)
