### ISSUE TITLE
Youtube middleware

### ISSUE THREAD

**Issue by filipecrosk** [sandiegojs/sandiegojs#3]
Much like the Meetup integration, let's hookup to the [sandiegojs channel on youtube](https://www.youtube.com/user/SanDiegoJS) so that users can view the available videos and see most recent.
## **Subtasks**
- [ ] GET api/v1/videos action
- [ ] YouTube module to retrieve videos - middleware
- [ ] Serialize response to JSONAPI spec
- [ ] Testing!
## **Resources**

[Join our Slack](http://sandiegojs.herokuapp.com/) and join the `#sdjs-website` channel
Checkout the [sandiegojs ember appi](https://github.com/sandiegojs/sandiegojs-api/issues/9)
